// <auto-generated />
namespace oncloud.Web.oddBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddId));
        
        string IMigrationMetadata.Id
        {
            get { return "201511201509589_AddId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
