// <auto-generated />
namespace oncloud.Web.oddBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_image_road_signs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_image_road_signs));
        
        string IMigrationMetadata.Id
        {
            get { return "201510221245393_added_image_road_signs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
