//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oncloud.Web.oddBase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int id { get; set; }
        public int Name { get; set; }
        public string BreadthS { get; set; }
        public string LengthS { get; set; }
        public string BreadthE { get; set; }
        public string LengthE { get; set; }
        public int Street_id { get; set; }
    
        public virtual Street Street { get; set; }
    }
}
