// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static oncloud.Web.oddBase.Controllers.AccountController Account = new oncloud.Web.oddBase.Controllers.T4MVC_AccountController();
    public static oncloud.Web.oddBase.Controllers.AdministrationController Administration = new oncloud.Web.oddBase.Controllers.T4MVC_AdministrationController();
    public static oncloud.Web.oddBase.Controllers.CitiesController Cities = new oncloud.Web.oddBase.Controllers.T4MVC_CitiesController();
    public static oncloud.Web.oddBase.Controllers.HomeController Home = new oncloud.Web.oddBase.Controllers.T4MVC_HomeController();
    public static oncloud.Web.oddBase.Controllers.HorizontalRoadMarkingsController HorizontalRoadMarkings = new oncloud.Web.oddBase.Controllers.T4MVC_HorizontalRoadMarkingsController();
    public static oncloud.Web.oddBase.Controllers.ManageController Manage = new oncloud.Web.oddBase.Controllers.T4MVC_ManageController();
    public static oncloud.Web.oddBase.Controllers.RoadBarriersController RoadBarriers = new oncloud.Web.oddBase.Controllers.T4MVC_RoadBarriersController();
    public static oncloud.Web.oddBase.Controllers.RoadSignsController RoadSigns = new oncloud.Web.oddBase.Controllers.T4MVC_RoadSignsController();
    public static oncloud.Web.oddBase.Controllers.StreetsController Streets = new oncloud.Web.oddBase.Controllers.T4MVC_StreetsController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileContentResult : System.Web.Mvc.FileContentResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileContentResult(string area, string controller, string action, string protocol = null): base(new byte[0], " ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jqGrid {
            private const string URLPATH = "~/Scripts/jqGrid";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class addons {
                private const string URLPATH = "~/Scripts/jqGrid/addons";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string ui_multiselect_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ui.multiselect.min.js") ? Url("ui.multiselect.min.js") : Url("ui.multiselect.js");
            }
        
            public static readonly string grid_base_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.base.min.js") ? Url("grid.base.min.js") : Url("grid.base.js");
            public static readonly string grid_celledit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.celledit.min.js") ? Url("grid.celledit.min.js") : Url("grid.celledit.js");
            public static readonly string grid_common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.common.min.js") ? Url("grid.common.min.js") : Url("grid.common.js");
            public static readonly string grid_filter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.filter.min.js") ? Url("grid.filter.min.js") : Url("grid.filter.js");
            public static readonly string grid_formedit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.formedit.min.js") ? Url("grid.formedit.min.js") : Url("grid.formedit.js");
            public static readonly string grid_grouping_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.grouping.min.js") ? Url("grid.grouping.min.js") : Url("grid.grouping.js");
            public static readonly string grid_import___Copy_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.import - Copy.min.js") ? Url("grid.import - Copy.min.js") : Url("grid.import - Copy.js");
            public static readonly string grid_import_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.import.min.js") ? Url("grid.import.min.js") : Url("grid.import.js");
            public static readonly string grid_inlinedit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.inlinedit.min.js") ? Url("grid.inlinedit.min.js") : Url("grid.inlinedit.js");
            public static readonly string grid_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.jqueryui.min.js") ? Url("grid.jqueryui.min.js") : Url("grid.jqueryui.js");
            public static readonly string grid_pivot_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.pivot.min.js") ? Url("grid.pivot.min.js") : Url("grid.pivot.js");
            public static readonly string grid_subgrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.subgrid.min.js") ? Url("grid.subgrid.min.js") : Url("grid.subgrid.js");
            public static readonly string grid_treegrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.treegrid.min.js") ? Url("grid.treegrid.min.js") : Url("grid.treegrid.js");
            public static readonly string grid_utils_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.utils.min.js") ? Url("grid.utils.min.js") : Url("grid.utils.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class i18n {
                private const string URLPATH = "~/Scripts/jqGrid/i18n";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string grid_locale_ar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ar.min.js") ? Url("grid.locale-ar.min.js") : Url("grid.locale-ar.js");
                public static readonly string grid_locale_bg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-bg.min.js") ? Url("grid.locale-bg.min.js") : Url("grid.locale-bg.js");
                public static readonly string grid_locale_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ca.min.js") ? Url("grid.locale-ca.min.js") : Url("grid.locale-ca.js");
                public static readonly string grid_locale_cn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-cn.min.js") ? Url("grid.locale-cn.min.js") : Url("grid.locale-cn.js");
                public static readonly string grid_locale_cs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-cs.min.js") ? Url("grid.locale-cs.min.js") : Url("grid.locale-cs.js");
                public static readonly string grid_locale_de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-de.min.js") ? Url("grid.locale-de.min.js") : Url("grid.locale-de.js");
                public static readonly string grid_locale_dk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-dk.min.js") ? Url("grid.locale-dk.min.js") : Url("grid.locale-dk.js");
                public static readonly string grid_locale_el_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-el.min.js") ? Url("grid.locale-el.min.js") : Url("grid.locale-el.js");
                public static readonly string grid_locale_en_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-en.min.js") ? Url("grid.locale-en.min.js") : Url("grid.locale-en.js");
                public static readonly string grid_locale_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-es.min.js") ? Url("grid.locale-es.min.js") : Url("grid.locale-es.js");
                public static readonly string grid_locale_fa_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-fa.min.js") ? Url("grid.locale-fa.min.js") : Url("grid.locale-fa.js");
                public static readonly string grid_locale_fi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-fi.min.js") ? Url("grid.locale-fi.min.js") : Url("grid.locale-fi.js");
                public static readonly string grid_locale_fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-fr.min.js") ? Url("grid.locale-fr.min.js") : Url("grid.locale-fr.js");
                public static readonly string grid_locale_gl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-gl.min.js") ? Url("grid.locale-gl.min.js") : Url("grid.locale-gl.js");
                public static readonly string grid_locale_he_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-he.min.js") ? Url("grid.locale-he.min.js") : Url("grid.locale-he.js");
                public static readonly string grid_locale_hr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-hr.min.js") ? Url("grid.locale-hr.min.js") : Url("grid.locale-hr.js");
                public static readonly string grid_locale_hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-hu.min.js") ? Url("grid.locale-hu.min.js") : Url("grid.locale-hu.js");
                public static readonly string grid_locale_id_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-id.min.js") ? Url("grid.locale-id.min.js") : Url("grid.locale-id.js");
                public static readonly string grid_locale_is_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-is.min.js") ? Url("grid.locale-is.min.js") : Url("grid.locale-is.js");
                public static readonly string grid_locale_it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-it.min.js") ? Url("grid.locale-it.min.js") : Url("grid.locale-it.js");
                public static readonly string grid_locale_ja_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ja.min.js") ? Url("grid.locale-ja.min.js") : Url("grid.locale-ja.js");
                public static readonly string grid_locale_kr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-kr.min.js") ? Url("grid.locale-kr.min.js") : Url("grid.locale-kr.js");
                public static readonly string grid_locale_lt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-lt.min.js") ? Url("grid.locale-lt.min.js") : Url("grid.locale-lt.js");
                public static readonly string grid_locale_me_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-me.min.js") ? Url("grid.locale-me.min.js") : Url("grid.locale-me.js");
                public static readonly string grid_locale_nl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-nl.min.js") ? Url("grid.locale-nl.min.js") : Url("grid.locale-nl.js");
                public static readonly string grid_locale_no_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-no.min.js") ? Url("grid.locale-no.min.js") : Url("grid.locale-no.js");
                public static readonly string grid_locale_pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-pl.min.js") ? Url("grid.locale-pl.min.js") : Url("grid.locale-pl.js");
                public static readonly string grid_locale_pt_br_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-pt-br.min.js") ? Url("grid.locale-pt-br.min.js") : Url("grid.locale-pt-br.js");
                public static readonly string grid_locale_pt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-pt.min.js") ? Url("grid.locale-pt.min.js") : Url("grid.locale-pt.js");
                public static readonly string grid_locale_ro_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ro.min.js") ? Url("grid.locale-ro.min.js") : Url("grid.locale-ro.js");
                public static readonly string grid_locale_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ru.min.js") ? Url("grid.locale-ru.min.js") : Url("grid.locale-ru.js");
                public static readonly string grid_locale_sk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sk.min.js") ? Url("grid.locale-sk.min.js") : Url("grid.locale-sk.js");
                public static readonly string grid_locale_sr_latin_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sr-latin.min.js") ? Url("grid.locale-sr-latin.min.js") : Url("grid.locale-sr-latin.js");
                public static readonly string grid_locale_sr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sr.min.js") ? Url("grid.locale-sr.min.js") : Url("grid.locale-sr.js");
                public static readonly string grid_locale_sv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sv.min.js") ? Url("grid.locale-sv.min.js") : Url("grid.locale-sv.js");
                public static readonly string grid_locale_th_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-th.min.js") ? Url("grid.locale-th.min.js") : Url("grid.locale-th.js");
                public static readonly string grid_locale_tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-tr.min.js") ? Url("grid.locale-tr.min.js") : Url("grid.locale-tr.js");
                public static readonly string grid_locale_tw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-tw.min.js") ? Url("grid.locale-tw.min.js") : Url("grid.locale-tw.js");
                public static readonly string grid_locale_uk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-uk.min.js") ? Url("grid.locale-uk.min.js") : Url("grid.locale-uk.js");
                public static readonly string grid_locale_vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-vi.min.js") ? Url("grid.locale-vi.min.js") : Url("grid.locale-vi.js");
            }
        
            public static readonly string jqDnR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqDnR.min.js") ? Url("jqDnR.min.js") : Url("jqDnR.js");
            public static readonly string jqGrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqGrid.min.js") ? Url("jqGrid.min.js") : Url("jqGrid.js");
            public static readonly string jqModal_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqModal.min.js") ? Url("jqModal.min.js") : Url("jqModal.js");
            public static readonly string jquery_fmatter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fmatter.min.js") ? Url("jquery.fmatter.min.js") : Url("jquery.fmatter.js");
            public static readonly string jquery_jqGrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.jqGrid.min.js") ? Url("jquery.jqGrid.min.js") : Url("jquery.jqGrid.js");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class minified {
                private const string URLPATH = "~/Scripts/jqGrid/minified";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string grid_base_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.base.min.js") ? Url("grid.base.min.js") : Url("grid.base.js");
                public static readonly string grid_celledit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.celledit.min.js") ? Url("grid.celledit.min.js") : Url("grid.celledit.js");
                public static readonly string grid_common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.common.min.js") ? Url("grid.common.min.js") : Url("grid.common.js");
                public static readonly string grid_filter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.filter.min.js") ? Url("grid.filter.min.js") : Url("grid.filter.js");
                public static readonly string grid_formedit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.formedit.min.js") ? Url("grid.formedit.min.js") : Url("grid.formedit.js");
                public static readonly string grid_grouping_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.grouping.min.js") ? Url("grid.grouping.min.js") : Url("grid.grouping.js");
                public static readonly string grid_import_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.import.min.js") ? Url("grid.import.min.js") : Url("grid.import.js");
                public static readonly string grid_inlinedit_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.inlinedit.min.js") ? Url("grid.inlinedit.min.js") : Url("grid.inlinedit.js");
                public static readonly string grid_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.jqueryui.min.js") ? Url("grid.jqueryui.min.js") : Url("grid.jqueryui.js");
                public static readonly string grid_pivot_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.pivot.min.js") ? Url("grid.pivot.min.js") : Url("grid.pivot.js");
                public static readonly string grid_subgrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.subgrid.min.js") ? Url("grid.subgrid.min.js") : Url("grid.subgrid.js");
                public static readonly string grid_treegrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.treegrid.min.js") ? Url("grid.treegrid.min.js") : Url("grid.treegrid.js");
                public static readonly string grid_utils_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.utils.min.js") ? Url("grid.utils.min.js") : Url("grid.utils.js");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class i18n {
                    private const string URLPATH = "~/Scripts/jqGrid/minified/i18n";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string grid_locale_ar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ar.min.js") ? Url("grid.locale-ar.min.js") : Url("grid.locale-ar.js");
                    public static readonly string grid_locale_bg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-bg.min.js") ? Url("grid.locale-bg.min.js") : Url("grid.locale-bg.js");
                    public static readonly string grid_locale_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ca.min.js") ? Url("grid.locale-ca.min.js") : Url("grid.locale-ca.js");
                    public static readonly string grid_locale_cn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-cn.min.js") ? Url("grid.locale-cn.min.js") : Url("grid.locale-cn.js");
                    public static readonly string grid_locale_cs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-cs.min.js") ? Url("grid.locale-cs.min.js") : Url("grid.locale-cs.js");
                    public static readonly string grid_locale_de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-de.min.js") ? Url("grid.locale-de.min.js") : Url("grid.locale-de.js");
                    public static readonly string grid_locale_dk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-dk.min.js") ? Url("grid.locale-dk.min.js") : Url("grid.locale-dk.js");
                    public static readonly string grid_locale_el_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-el.min.js") ? Url("grid.locale-el.min.js") : Url("grid.locale-el.js");
                    public static readonly string grid_locale_en_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-en.min.js") ? Url("grid.locale-en.min.js") : Url("grid.locale-en.js");
                    public static readonly string grid_locale_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-es.min.js") ? Url("grid.locale-es.min.js") : Url("grid.locale-es.js");
                    public static readonly string grid_locale_fa_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-fa.min.js") ? Url("grid.locale-fa.min.js") : Url("grid.locale-fa.js");
                    public static readonly string grid_locale_fi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-fi.min.js") ? Url("grid.locale-fi.min.js") : Url("grid.locale-fi.js");
                    public static readonly string grid_locale_fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-fr.min.js") ? Url("grid.locale-fr.min.js") : Url("grid.locale-fr.js");
                    public static readonly string grid_locale_gl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-gl.min.js") ? Url("grid.locale-gl.min.js") : Url("grid.locale-gl.js");
                    public static readonly string grid_locale_he_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-he.min.js") ? Url("grid.locale-he.min.js") : Url("grid.locale-he.js");
                    public static readonly string grid_locale_hr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-hr.min.js") ? Url("grid.locale-hr.min.js") : Url("grid.locale-hr.js");
                    public static readonly string grid_locale_hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-hu.min.js") ? Url("grid.locale-hu.min.js") : Url("grid.locale-hu.js");
                    public static readonly string grid_locale_id_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-id.min.js") ? Url("grid.locale-id.min.js") : Url("grid.locale-id.js");
                    public static readonly string grid_locale_is_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-is.min.js") ? Url("grid.locale-is.min.js") : Url("grid.locale-is.js");
                    public static readonly string grid_locale_it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-it.min.js") ? Url("grid.locale-it.min.js") : Url("grid.locale-it.js");
                    public static readonly string grid_locale_ja_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ja.min.js") ? Url("grid.locale-ja.min.js") : Url("grid.locale-ja.js");
                    public static readonly string grid_locale_kr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-kr.min.js") ? Url("grid.locale-kr.min.js") : Url("grid.locale-kr.js");
                    public static readonly string grid_locale_lt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-lt.min.js") ? Url("grid.locale-lt.min.js") : Url("grid.locale-lt.js");
                    public static readonly string grid_locale_me_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-me.min.js") ? Url("grid.locale-me.min.js") : Url("grid.locale-me.js");
                    public static readonly string grid_locale_nl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-nl.min.js") ? Url("grid.locale-nl.min.js") : Url("grid.locale-nl.js");
                    public static readonly string grid_locale_no_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-no.min.js") ? Url("grid.locale-no.min.js") : Url("grid.locale-no.js");
                    public static readonly string grid_locale_pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-pl.min.js") ? Url("grid.locale-pl.min.js") : Url("grid.locale-pl.js");
                    public static readonly string grid_locale_pt_br_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-pt-br.min.js") ? Url("grid.locale-pt-br.min.js") : Url("grid.locale-pt-br.js");
                    public static readonly string grid_locale_pt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-pt.min.js") ? Url("grid.locale-pt.min.js") : Url("grid.locale-pt.js");
                    public static readonly string grid_locale_ro_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ro.min.js") ? Url("grid.locale-ro.min.js") : Url("grid.locale-ro.js");
                    public static readonly string grid_locale_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ru.min.js") ? Url("grid.locale-ru.min.js") : Url("grid.locale-ru.js");
                    public static readonly string grid_locale_sk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sk.min.js") ? Url("grid.locale-sk.min.js") : Url("grid.locale-sk.js");
                    public static readonly string grid_locale_sr_latin_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sr-latin.min.js") ? Url("grid.locale-sr-latin.min.js") : Url("grid.locale-sr-latin.js");
                    public static readonly string grid_locale_sr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sr.min.js") ? Url("grid.locale-sr.min.js") : Url("grid.locale-sr.js");
                    public static readonly string grid_locale_sv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-sv.min.js") ? Url("grid.locale-sv.min.js") : Url("grid.locale-sv.js");
                    public static readonly string grid_locale_th_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-th.min.js") ? Url("grid.locale-th.min.js") : Url("grid.locale-th.js");
                    public static readonly string grid_locale_tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-tr.min.js") ? Url("grid.locale-tr.min.js") : Url("grid.locale-tr.js");
                    public static readonly string grid_locale_tw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-tw.min.js") ? Url("grid.locale-tw.min.js") : Url("grid.locale-tw.js");
                    public static readonly string grid_locale_ua_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-ua.min.js") ? Url("grid.locale-ua.min.js") : Url("grid.locale-ua.js");
                    public static readonly string grid_locale_vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-vi.min.js") ? Url("grid.locale-vi.min.js") : Url("grid.locale-vi.js");
                }
            
                public static readonly string jqDnR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqDnR.min.js") ? Url("jqDnR.min.js") : Url("jqDnR.js");
                public static readonly string jqModal_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqModal.min.js") ? Url("jqModal.min.js") : Url("jqModal.js");
                public static readonly string jquery_fmatter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fmatter.min.js") ? Url("jquery.fmatter.min.js") : Url("jquery.fmatter.js");
                public static readonly string jquery_jqGrid_min_js = Url("jquery.jqGrid.min.js");
                public static readonly string jquery_jqGrid_min_js_map = Url("jquery.jqGrid.min.js.map");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class plugins {
                private const string URLPATH = "~/Scripts/jqGrid/plugins";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string grid_addons_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.addons.min.js") ? Url("grid.addons.min.js") : Url("grid.addons.js");
                public static readonly string grid_postext_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.postext.min.js") ? Url("grid.postext.min.js") : Url("grid.postext.js");
                public static readonly string grid_setcolumns_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.setcolumns.min.js") ? Url("grid.setcolumns.min.js") : Url("grid.setcolumns.js");
                public static readonly string grid_tbltogrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.tbltogrid.min.js") ? Url("grid.tbltogrid.min.js") : Url("grid.tbltogrid.js");
                public static readonly string jquery_contextmenu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.contextmenu.min.js") ? Url("jquery.contextmenu.min.js") : Url("jquery.contextmenu.js");
                public static readonly string jquery_searchFilter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.searchFilter.min.js") ? Url("jquery.searchFilter.min.js") : Url("jquery.searchFilter.js");
                public static readonly string jquery_tablednd_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.tablednd.min.js") ? Url("jquery.tablednd.min.js") : Url("jquery.tablednd.js");
            }
        
        }
    
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jquery_form {
            private const string URLPATH = "~/Scripts/jquery.form";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string jquery_form_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.form.min.js") ? Url("jquery.form.min.js") : Url("jquery.form.js");
            public static readonly string jquery_form_min_js = Url("jquery.form.min.js");
        }
    
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string ONCLOUD_logo_site_png = Url("ONCLOUD logo site.png");
            public static readonly string ui_bg_diagonals_thick_18_b81900_40x40_png = Url("ui-bg_diagonals-thick_18_b81900_40x40.png");
            public static readonly string ui_bg_diagonals_thick_20_666666_40x40_png = Url("ui-bg_diagonals-thick_20_666666_40x40.png");
            public static readonly string ui_bg_flat_10_000000_40x100_png = Url("ui-bg_flat_10_000000_40x100.png");
            public static readonly string ui_bg_glass_100_f6f6f6_1x400_png = Url("ui-bg_glass_100_f6f6f6_1x400.png");
            public static readonly string ui_bg_glass_100_fdf5ce_1x400_png = Url("ui-bg_glass_100_fdf5ce_1x400.png");
            public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
            public static readonly string ui_bg_gloss_wave_35_f6a828_500x100_png = Url("ui-bg_gloss-wave_35_f6a828_500x100.png");
            public static readonly string ui_bg_highlight_soft_100_eeeeee_1x100_png = Url("ui-bg_highlight-soft_100_eeeeee_1x100.png");
            public static readonly string ui_bg_highlight_soft_75_ffe45c_1x100_png = Url("ui-bg_highlight-soft_75_ffe45c_1x100.png");
            public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
            public static readonly string ui_icons_228ef1_256x240_png = Url("ui-icons_228ef1_256x240.png");
            public static readonly string ui_icons_ef8c08_256x240_png = Url("ui-icons_ef8c08_256x240.png");
            public static readonly string ui_icons_ffd27a_256x240_png = Url("ui-icons_ffd27a_256x240.png");
            public static readonly string ui_icons_ffffff_256x240_png = Url("ui-icons_ffffff_256x240.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jqGrid {
            private const string URLPATH = "~/Content/jqGrid";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string searchFilter_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/searchFilter.min.css") ? Url("searchFilter.min.css") : Url("searchFilter.css");
                 
            public static readonly string ui_jqgrid_bootstarp_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ui.jqgrid-bootstarp.min.css") ? Url("ui.jqgrid-bootstarp.min.css") : Url("ui.jqgrid-bootstarp.css");
                 
            public static readonly string ui_jqgrid_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ui.jqgrid.min.css") ? Url("ui.jqgrid.min.css") : Url("ui.jqgrid.css");
                 
            public static readonly string ui_multiselect_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ui.multiselect.min.css") ? Url("ui.multiselect.min.css") : Url("ui.multiselect.css");
                 
        }
    
        public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jQuery_FileUpload {
            private const string URLPATH = "~/Content/jQuery.FileUpload";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                private const string URLPATH = "~/Content/jQuery.FileUpload/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string jquery_fileupload_noscript_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fileupload-noscript.min.css") ? Url("jquery.fileupload-noscript.min.css") : Url("jquery.fileupload-noscript.css");
                     
                public static readonly string jquery_fileupload_ui_noscript_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fileupload-ui-noscript.min.css") ? Url("jquery.fileupload-ui-noscript.min.css") : Url("jquery.fileupload-ui-noscript.css");
                     
                public static readonly string jquery_fileupload_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fileupload-ui.min.css") ? Url("jquery.fileupload-ui.min.css") : Url("jquery.fileupload-ui.css");
                     
                public static readonly string jquery_fileupload_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fileupload.min.css") ? Url("jquery.fileupload.min.css") : Url("jquery.fileupload.css");
                     
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class img {
                private const string URLPATH = "~/Content/jQuery.FileUpload/img";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string loading_gif = Url("loading.gif");
                public static readonly string progressbar_gif = Url("progressbar.gif");
            }
        
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                     
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                     
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                     
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                     
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                     
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                     
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                     
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                     
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                     
                public static readonly string jquery_ui_menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.menu.min.css") ? Url("jquery.ui.menu.min.css") : Url("jquery.ui.menu.css");
                     
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                     
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                     
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                     
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                     
                public static readonly string jquery_ui_spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.spinner.min.css") ? Url("jquery.ui.spinner.min.css") : Url("jquery.ui.spinner.css");
                     
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                     
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                     
                public static readonly string jquery_ui_tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tooltip.min.css") ? Url("jquery.ui.tooltip.min.css") : Url("jquery.ui.tooltip.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    private const string URLPATH = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        private const string URLPATH = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                        public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                        public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                        public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                        public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                        public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                        public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                        public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                        public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                        public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    }
                
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_ui_accordion_min_css = Url("jquery.ui.accordion.min.css");
                    public static readonly string jquery_ui_autocomplete_min_css = Url("jquery.ui.autocomplete.min.css");
                    public static readonly string jquery_ui_button_min_css = Url("jquery.ui.button.min.css");
                    public static readonly string jquery_ui_core_min_css = Url("jquery.ui.core.min.css");
                    public static readonly string jquery_ui_datepicker_min_css = Url("jquery.ui.datepicker.min.css");
                    public static readonly string jquery_ui_dialog_min_css = Url("jquery.ui.dialog.min.css");
                    public static readonly string jquery_ui_menu_min_css = Url("jquery.ui.menu.min.css");
                    public static readonly string jquery_ui_progressbar_min_css = Url("jquery.ui.progressbar.min.css");
                    public static readonly string jquery_ui_resizable_min_css = Url("jquery.ui.resizable.min.css");
                    public static readonly string jquery_ui_selectable_min_css = Url("jquery.ui.selectable.min.css");
                    public static readonly string jquery_ui_slider_min_css = Url("jquery.ui.slider.min.css");
                    public static readonly string jquery_ui_spinner_min_css = Url("jquery.ui.spinner.min.css");
                    public static readonly string jquery_ui_tabs_min_css = Url("jquery.ui.tabs.min.css");
                    public static readonly string jquery_ui_theme_min_css = Url("jquery.ui.theme.min.css");
                    public static readonly string jquery_ui_tooltip_min_css = Url("jquery.ui.tooltip.min.css");
                }
            
            }
        
        }
    
        public static readonly string СorrectionBootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/СorrectionBootstrap.min.css") ? Url("СorrectionBootstrap.min.css") : Url("СorrectionBootstrap.css");
             
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class jqGrid 
            {
                public static partial class addons 
                {
                    public static class Assets
                    {
                        public const string ui_multiselect_js = "~/Scripts/jqGrid/addons/ui.multiselect.js"; 
                    }
                }
                public static partial class i18n 
                {
                    public static class Assets
                    {
                        public const string grid_locale_ar_js = "~/Scripts/jqGrid/i18n/grid.locale-ar.js"; 
                        public const string grid_locale_bg_js = "~/Scripts/jqGrid/i18n/grid.locale-bg.js"; 
                        public const string grid_locale_ca_js = "~/Scripts/jqGrid/i18n/grid.locale-ca.js"; 
                        public const string grid_locale_cn_js = "~/Scripts/jqGrid/i18n/grid.locale-cn.js"; 
                        public const string grid_locale_cs_js = "~/Scripts/jqGrid/i18n/grid.locale-cs.js"; 
                        public const string grid_locale_de_js = "~/Scripts/jqGrid/i18n/grid.locale-de.js"; 
                        public const string grid_locale_dk_js = "~/Scripts/jqGrid/i18n/grid.locale-dk.js"; 
                        public const string grid_locale_el_js = "~/Scripts/jqGrid/i18n/grid.locale-el.js"; 
                        public const string grid_locale_en_js = "~/Scripts/jqGrid/i18n/grid.locale-en.js"; 
                        public const string grid_locale_es_js = "~/Scripts/jqGrid/i18n/grid.locale-es.js"; 
                        public const string grid_locale_fa_js = "~/Scripts/jqGrid/i18n/grid.locale-fa.js"; 
                        public const string grid_locale_fi_js = "~/Scripts/jqGrid/i18n/grid.locale-fi.js"; 
                        public const string grid_locale_fr_js = "~/Scripts/jqGrid/i18n/grid.locale-fr.js"; 
                        public const string grid_locale_gl_js = "~/Scripts/jqGrid/i18n/grid.locale-gl.js"; 
                        public const string grid_locale_he_js = "~/Scripts/jqGrid/i18n/grid.locale-he.js"; 
                        public const string grid_locale_hr_js = "~/Scripts/jqGrid/i18n/grid.locale-hr.js"; 
                        public const string grid_locale_hu_js = "~/Scripts/jqGrid/i18n/grid.locale-hu.js"; 
                        public const string grid_locale_id_js = "~/Scripts/jqGrid/i18n/grid.locale-id.js"; 
                        public const string grid_locale_is_js = "~/Scripts/jqGrid/i18n/grid.locale-is.js"; 
                        public const string grid_locale_it_js = "~/Scripts/jqGrid/i18n/grid.locale-it.js"; 
                        public const string grid_locale_ja_js = "~/Scripts/jqGrid/i18n/grid.locale-ja.js"; 
                        public const string grid_locale_kr_js = "~/Scripts/jqGrid/i18n/grid.locale-kr.js"; 
                        public const string grid_locale_lt_js = "~/Scripts/jqGrid/i18n/grid.locale-lt.js"; 
                        public const string grid_locale_me_js = "~/Scripts/jqGrid/i18n/grid.locale-me.js"; 
                        public const string grid_locale_nl_js = "~/Scripts/jqGrid/i18n/grid.locale-nl.js"; 
                        public const string grid_locale_no_js = "~/Scripts/jqGrid/i18n/grid.locale-no.js"; 
                        public const string grid_locale_pl_js = "~/Scripts/jqGrid/i18n/grid.locale-pl.js"; 
                        public const string grid_locale_pt_br_js = "~/Scripts/jqGrid/i18n/grid.locale-pt-br.js"; 
                        public const string grid_locale_pt_js = "~/Scripts/jqGrid/i18n/grid.locale-pt.js"; 
                        public const string grid_locale_ro_js = "~/Scripts/jqGrid/i18n/grid.locale-ro.js"; 
                        public const string grid_locale_ru_js = "~/Scripts/jqGrid/i18n/grid.locale-ru.js"; 
                        public const string grid_locale_sk_js = "~/Scripts/jqGrid/i18n/grid.locale-sk.js"; 
                        public const string grid_locale_sr_latin_js = "~/Scripts/jqGrid/i18n/grid.locale-sr-latin.js"; 
                        public const string grid_locale_sr_js = "~/Scripts/jqGrid/i18n/grid.locale-sr.js"; 
                        public const string grid_locale_sv_js = "~/Scripts/jqGrid/i18n/grid.locale-sv.js"; 
                        public const string grid_locale_th_js = "~/Scripts/jqGrid/i18n/grid.locale-th.js"; 
                        public const string grid_locale_tr_js = "~/Scripts/jqGrid/i18n/grid.locale-tr.js"; 
                        public const string grid_locale_tw_js = "~/Scripts/jqGrid/i18n/grid.locale-tw.js"; 
                        public const string grid_locale_uk_js = "~/Scripts/jqGrid/i18n/grid.locale-uk.js"; 
                        public const string grid_locale_vi_js = "~/Scripts/jqGrid/i18n/grid.locale-vi.js"; 
                    }
                }
                public static partial class minified 
                {
                    public static partial class i18n 
                    {
                        public static class Assets
                        {
                            public const string grid_locale_ar_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-ar.js"; 
                            public const string grid_locale_bg_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-bg.js"; 
                            public const string grid_locale_ca_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-ca.js"; 
                            public const string grid_locale_cn_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-cn.js"; 
                            public const string grid_locale_cs_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-cs.js"; 
                            public const string grid_locale_de_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-de.js"; 
                            public const string grid_locale_dk_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-dk.js"; 
                            public const string grid_locale_el_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-el.js"; 
                            public const string grid_locale_en_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-en.js"; 
                            public const string grid_locale_es_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-es.js"; 
                            public const string grid_locale_fa_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-fa.js"; 
                            public const string grid_locale_fi_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-fi.js"; 
                            public const string grid_locale_fr_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-fr.js"; 
                            public const string grid_locale_gl_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-gl.js"; 
                            public const string grid_locale_he_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-he.js"; 
                            public const string grid_locale_hr_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-hr.js"; 
                            public const string grid_locale_hu_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-hu.js"; 
                            public const string grid_locale_id_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-id.js"; 
                            public const string grid_locale_is_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-is.js"; 
                            public const string grid_locale_it_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-it.js"; 
                            public const string grid_locale_ja_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-ja.js"; 
                            public const string grid_locale_kr_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-kr.js"; 
                            public const string grid_locale_lt_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-lt.js"; 
                            public const string grid_locale_me_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-me.js"; 
                            public const string grid_locale_nl_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-nl.js"; 
                            public const string grid_locale_no_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-no.js"; 
                            public const string grid_locale_pl_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-pl.js"; 
                            public const string grid_locale_pt_br_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-pt-br.js"; 
                            public const string grid_locale_pt_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-pt.js"; 
                            public const string grid_locale_ro_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-ro.js"; 
                            public const string grid_locale_ru_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-ru.js"; 
                            public const string grid_locale_sk_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-sk.js"; 
                            public const string grid_locale_sr_latin_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-sr-latin.js"; 
                            public const string grid_locale_sr_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-sr.js"; 
                            public const string grid_locale_sv_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-sv.js"; 
                            public const string grid_locale_th_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-th.js"; 
                            public const string grid_locale_tr_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-tr.js"; 
                            public const string grid_locale_tw_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-tw.js"; 
                            public const string grid_locale_ua_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-ua.js"; 
                            public const string grid_locale_vi_js = "~/Scripts/jqGrid/minified/i18n/grid.locale-vi.js"; 
                        }
                    }
                    public static class Assets
                    {
                        public const string grid_base_js = "~/Scripts/jqGrid/minified/grid.base.js"; 
                        public const string grid_celledit_js = "~/Scripts/jqGrid/minified/grid.celledit.js"; 
                        public const string grid_common_js = "~/Scripts/jqGrid/minified/grid.common.js"; 
                        public const string grid_filter_js = "~/Scripts/jqGrid/minified/grid.filter.js"; 
                        public const string grid_formedit_js = "~/Scripts/jqGrid/minified/grid.formedit.js"; 
                        public const string grid_grouping_js = "~/Scripts/jqGrid/minified/grid.grouping.js"; 
                        public const string grid_import_js = "~/Scripts/jqGrid/minified/grid.import.js"; 
                        public const string grid_inlinedit_js = "~/Scripts/jqGrid/minified/grid.inlinedit.js"; 
                        public const string grid_jqueryui_js = "~/Scripts/jqGrid/minified/grid.jqueryui.js"; 
                        public const string grid_pivot_js = "~/Scripts/jqGrid/minified/grid.pivot.js"; 
                        public const string grid_subgrid_js = "~/Scripts/jqGrid/minified/grid.subgrid.js"; 
                        public const string grid_treegrid_js = "~/Scripts/jqGrid/minified/grid.treegrid.js"; 
                        public const string grid_utils_js = "~/Scripts/jqGrid/minified/grid.utils.js"; 
                        public const string jqDnR_js = "~/Scripts/jqGrid/minified/jqDnR.js"; 
                        public const string jqModal_js = "~/Scripts/jqGrid/minified/jqModal.js"; 
                        public const string jquery_fmatter_js = "~/Scripts/jqGrid/minified/jquery.fmatter.js"; 
                        public const string jquery_jqGrid_min_js = "~/Scripts/jqGrid/minified/jquery.jqGrid.min.js"; 
                    }
                }
                public static partial class plugins 
                {
                    public static class Assets
                    {
                        public const string grid_addons_js = "~/Scripts/jqGrid/plugins/grid.addons.js"; 
                        public const string grid_postext_js = "~/Scripts/jqGrid/plugins/grid.postext.js"; 
                        public const string grid_setcolumns_js = "~/Scripts/jqGrid/plugins/grid.setcolumns.js"; 
                        public const string grid_tbltogrid_js = "~/Scripts/jqGrid/plugins/grid.tbltogrid.js"; 
                        public const string jquery_contextmenu_js = "~/Scripts/jqGrid/plugins/jquery.contextmenu.js"; 
                        public const string jquery_searchFilter_js = "~/Scripts/jqGrid/plugins/jquery.searchFilter.js"; 
                        public const string jquery_tablednd_js = "~/Scripts/jqGrid/plugins/jquery.tablednd.js"; 
                    }
                }
                public static class Assets
                {
                    public const string grid_base_js = "~/Scripts/jqGrid/grid.base.js"; 
                    public const string grid_celledit_js = "~/Scripts/jqGrid/grid.celledit.js"; 
                    public const string grid_common_js = "~/Scripts/jqGrid/grid.common.js"; 
                    public const string grid_filter_js = "~/Scripts/jqGrid/grid.filter.js"; 
                    public const string grid_formedit_js = "~/Scripts/jqGrid/grid.formedit.js"; 
                    public const string grid_grouping_js = "~/Scripts/jqGrid/grid.grouping.js"; 
                    public const string grid_import___Copy_js = "~/Scripts/jqGrid/grid.import - Copy.js"; 
                    public const string grid_import_js = "~/Scripts/jqGrid/grid.import.js"; 
                    public const string grid_inlinedit_js = "~/Scripts/jqGrid/grid.inlinedit.js"; 
                    public const string grid_jqueryui_js = "~/Scripts/jqGrid/grid.jqueryui.js"; 
                    public const string grid_pivot_js = "~/Scripts/jqGrid/grid.pivot.js"; 
                    public const string grid_subgrid_js = "~/Scripts/jqGrid/grid.subgrid.js"; 
                    public const string grid_treegrid_js = "~/Scripts/jqGrid/grid.treegrid.js"; 
                    public const string grid_utils_js = "~/Scripts/jqGrid/grid.utils.js"; 
                    public const string jqDnR_js = "~/Scripts/jqGrid/jqDnR.js"; 
                    public const string jqGrid_js = "~/Scripts/jqGrid/jqGrid.js"; 
                    public const string jqModal_js = "~/Scripts/jqGrid/jqModal.js"; 
                    public const string jquery_fmatter_js = "~/Scripts/jqGrid/jquery.fmatter.js"; 
                    public const string jquery_jqGrid_js = "~/Scripts/jqGrid/jquery.jqGrid.js"; 
                }
            }
            public static partial class jquery_form 
            {
                public static class Assets
                {
                    public const string jquery_form_js = "~/Scripts/jquery.form/jquery.form.js"; 
                    public const string jquery_form_min_js = "~/Scripts/jquery.form/jquery.form.min.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static partial class jqGrid 
            {
                public static class Assets
                {
                    public const string searchFilter_css = "~/Content/jqGrid/searchFilter.css";
                    public const string ui_jqgrid_bootstarp_css = "~/Content/jqGrid/ui.jqgrid-bootstarp.css";
                    public const string ui_jqgrid_css = "~/Content/jqGrid/ui.jqgrid.css";
                    public const string ui_multiselect_css = "~/Content/jqGrid/ui.multiselect.css";
                }
            }
            public static partial class jQuery_FileUpload 
            {
                public static partial class css 
                {
                    public static class Assets
                    {
                        public const string jquery_fileupload_noscript_css = "~/Content/jQuery.FileUpload/css/jquery.fileupload-noscript.css";
                        public const string jquery_fileupload_ui_noscript_css = "~/Content/jQuery.FileUpload/css/jquery.fileupload-ui-noscript.css";
                        public const string jquery_fileupload_ui_css = "~/Content/jQuery.FileUpload/css/jquery.fileupload-ui.css";
                        public const string jquery_fileupload_css = "~/Content/jQuery.FileUpload/css/jquery.fileupload.css";
                    }
                }
                public static partial class img 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class minified 
                    {
                        public static partial class images 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                            public const string jquery_ui_min_css = "~/Content/themes/base/minified/jquery-ui.min.css";
                            public const string jquery_ui_accordion_min_css = "~/Content/themes/base/minified/jquery.ui.accordion.min.css";
                            public const string jquery_ui_autocomplete_min_css = "~/Content/themes/base/minified/jquery.ui.autocomplete.min.css";
                            public const string jquery_ui_button_min_css = "~/Content/themes/base/minified/jquery.ui.button.min.css";
                            public const string jquery_ui_core_min_css = "~/Content/themes/base/minified/jquery.ui.core.min.css";
                            public const string jquery_ui_datepicker_min_css = "~/Content/themes/base/minified/jquery.ui.datepicker.min.css";
                            public const string jquery_ui_dialog_min_css = "~/Content/themes/base/minified/jquery.ui.dialog.min.css";
                            public const string jquery_ui_menu_min_css = "~/Content/themes/base/minified/jquery.ui.menu.min.css";
                            public const string jquery_ui_progressbar_min_css = "~/Content/themes/base/minified/jquery.ui.progressbar.min.css";
                            public const string jquery_ui_resizable_min_css = "~/Content/themes/base/minified/jquery.ui.resizable.min.css";
                            public const string jquery_ui_selectable_min_css = "~/Content/themes/base/minified/jquery.ui.selectable.min.css";
                            public const string jquery_ui_slider_min_css = "~/Content/themes/base/minified/jquery.ui.slider.min.css";
                            public const string jquery_ui_spinner_min_css = "~/Content/themes/base/minified/jquery.ui.spinner.min.css";
                            public const string jquery_ui_tabs_min_css = "~/Content/themes/base/minified/jquery.ui.tabs.min.css";
                            public const string jquery_ui_theme_min_css = "~/Content/themes/base/minified/jquery.ui.theme.min.css";
                            public const string jquery_ui_tooltip_min_css = "~/Content/themes/base/minified/jquery.ui.tooltip.min.css";
                        }
                    }
                    public static class Assets
                    {
                        public const string jquery_ui_css = "~/Content/themes/base/jquery-ui.css";
                        public const string jquery_ui_accordion_css = "~/Content/themes/base/jquery.ui.accordion.css";
                        public const string jquery_ui_all_css = "~/Content/themes/base/jquery.ui.all.css";
                        public const string jquery_ui_autocomplete_css = "~/Content/themes/base/jquery.ui.autocomplete.css";
                        public const string jquery_ui_base_css = "~/Content/themes/base/jquery.ui.base.css";
                        public const string jquery_ui_button_css = "~/Content/themes/base/jquery.ui.button.css";
                        public const string jquery_ui_core_css = "~/Content/themes/base/jquery.ui.core.css";
                        public const string jquery_ui_datepicker_css = "~/Content/themes/base/jquery.ui.datepicker.css";
                        public const string jquery_ui_dialog_css = "~/Content/themes/base/jquery.ui.dialog.css";
                        public const string jquery_ui_menu_css = "~/Content/themes/base/jquery.ui.menu.css";
                        public const string jquery_ui_progressbar_css = "~/Content/themes/base/jquery.ui.progressbar.css";
                        public const string jquery_ui_resizable_css = "~/Content/themes/base/jquery.ui.resizable.css";
                        public const string jquery_ui_selectable_css = "~/Content/themes/base/jquery.ui.selectable.css";
                        public const string jquery_ui_slider_css = "~/Content/themes/base/jquery.ui.slider.css";
                        public const string jquery_ui_spinner_css = "~/Content/themes/base/jquery.ui.spinner.css";
                        public const string jquery_ui_tabs_css = "~/Content/themes/base/jquery.ui.tabs.css";
                        public const string jquery_ui_theme_css = "~/Content/themes/base/jquery.ui.theme.css";
                        public const string jquery_ui_tooltip_css = "~/Content/themes/base/jquery.ui.tooltip.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string jquery_ui_css = "~/Content/jquery-ui.css";
                public const string Site_css = "~/Content/Site.css";
                public const string СorrectionBootstrap_css = "~/Content/СorrectionBootstrap.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


